# -*- coding: utf-8 -*-
"""YOLO v4 - Detecção de objetos em vídeos com Darknet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFm95IwxPfSJxjNjFUzi6jEclBudjuuF

## **Detectando objetos com YOLO v4**

**Etapa 1 - Download do Darknet**
"""

!git clone https://github.com/AlexeyAB/darknet

cd darknet

ls

"""**Etapa 2 - Compilando a biblioteca**"""

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1' Makefile

import tensorflow as tf
device_name = tf.test.gpu_device_name()
print(device_name)

!make

"""**Etapa 3 - Baixando os pesos do modelo pré-treinado**"""

from google.colab import drive
drive.mount('/content/gdrive')

"""!mkdir darknet
!cd darknet
!wget -r -np -nH --cut-dirs=3 -R index.html https://github.com/AlexeyAB/darknet/
"""

import zipfile
path = "/content/gdrive/MyDrive/YOLO/modelo_YOLOv4.zip"
zip_object = zipfile.ZipFile(file = path, mode = "r")
zip_object.extractall("./")
zip_object.close()

"""**Etapa 4 - Carregando o vídeo**

4.1 - De uma url
"""

!wget http://github/gabevr/yolo/raw/master/videos/video_teste02.mp4

"""4.2 - Do Google Drive"""

!cp /content/gdrive/MyDrive/YOLO/videos/video_teste02.mp4 ./

!ls

"""**Etapa 5 - Realizando a detecção em vídeo**"""

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show video_teste02.mp4 -i 0 -out_filename resultado.avi

!du -h resultado.avi

"""**Etapa 6 - Visualizando o resultado**"""

!cp ./resultado.avi /content/gdrive/MyDrive/YOLO/videos/resultado1.avi

"""**Especificando um threshold**"""

!cp /content/gdrive/MyDrive/YOLO/videos/video_rua01.mp4 ./

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show video_rua01.mp4 -i 0 -out_filename resultado02.avi -thresh 0.3

!cp ./resultado02.avi /content/gdrive/MyDrive/YOLO/videos/resultado1.avi